In [1]:
import numpy as np

# Lista en python

In [2]:
L = [1,2,3]

# Array en numpy

In [3]:
A = np.array(L)

In [4]:
print(L)
print(A)

[1, 2, 3]
[1 2 3]


In [8]:
A[0:2] #SLICEN


array([1, 2])

# Array compuestos o anidados

In [11]:
A2 = np.array([[1,2,3],[5,6,7]])

In [12]:
print(A2)

[[1 2 3]
 [5 6 7]]


In [14]:
L2 = [[1,2,3],[5,6,7]] #Lista anidada
A2= np.array(L2)

In [15]:
print(L2)
print(A2)

[[1, 2, 3], [5, 6, 7]]
[[1, 2, 3], [5, 6, 7]]


In [17]:
##Array de ceros y unos

zeros_array = np.zeros ((2,3))
ones_array = np.ones((3,2))

print ("Array de ceros:\n", zeros_array)
print ("Array de unos:\n", ones_array)


Array de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array de unos:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [21]:
## Arrays de rangos
range_array = np.arange(10)
print ("Range Array: ", range_array)

Range Array:  [ 1  2  3  4  5  6  7  8  9 10]


In [27]:
## Array espacioados liealmente

linspace_array = np.linspace(-1, 2, num=5)

print("linspace_array: ", linspace_array)


linspace_array:  [-1.   -0.25  0.5   1.25  2.  ]


In [37]:
## Matriz identidad

identity_matrix = np.eye(5,6)
print("Matriz de identidad: ", identity_matrix)

Matriz de identidad:  [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [35]:
## Array con tipos de datos especificos
int_array = np.array([1,2,3], dtype='int32')
float_array = np.array([1,2,3], dtype='float32')
print("Integer Array: ", int_array)
print("Float Array: ", float_array)


Integer Array:  [1 2 3]
Float Array:  [1. 2. 3.]
