In [1]:
import numpy as np

In [2]:
vector = np.array([1,2,3])

In [3]:
vector+5

array([6, 7, 8])

In [5]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[1], [2], [3]])

In [6]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(B)

[[1]
 [2]
 [3]]


In [8]:
A*B

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])