In [1]:
import numpy as np

In [20]:
a = np.array([1,2,6])
b = np.array([4,5,6])

In [3]:
np.add(a,b)

array([5, 7, 9])

In [4]:
np.subtract(b,a)

array([3, 3, 3])

In [5]:
np.multiply(a,b)

array([ 4, 10, 18])

In [6]:
np.divide(b,a)

array([4. , 2.5, 2. ])

In [ ]:
##Funciones trigonometricas

In [7]:
angles = np.array([0,30,60,90])

In [8]:
np.sin(angles)

array([ 0.        , -0.98803162, -0.30481062,  0.89399666])

In [11]:
angles_rad = np.radians(angles)

In [12]:
np.sin(angles_rad)

array([0.       , 0.5      , 0.8660254, 1.       ])

In [13]:
np.cos(angles_rad)

array([1.00000000e+00, 8.66025404e-01, 5.00000000e-01, 6.12323400e-17])

In [14]:
np.tan(angles_rad)

array([0.00000000e+00, 5.77350269e-01, 1.73205081e+00, 1.63312394e+16])

In [ ]:
##Operaciones logicas

In [23]:
np.greater(b,a) ## compara si el primero es mayor que el segundo

array([ True,  True, False])

In [22]:
np.less(a,b) ## compara si el primero es menor que el segundo

array([ True,  True, False])

In [21]:
np.equal(a,b) ##compara si los dos valores son iguales

array([False, False,  True])

In [24]:
#Funciones exponenciales

In [25]:
np.power(a,b)

array([    1,    32, 46656])

In [26]:
np.mean(a) #media de a

np.float64(3.0)

In [27]:
np.std(b) #desviacion estandar

np.float64(0.816496580927726)

In [28]:
print(a)
print(b)

[1 2 6]
[4 5 6]
